FROM tensorflow/tensorflow:1.3.0-gpu-py3

ADD requirements.txt /install/requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /install/requirements.txt

# Set up our notebook config.
COPY docker/jupyter_notebook_config.py /root/.jupyter/
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension

WORKDIR /notebooks

CMD /run_jupyter.sh --allow-root
